#!/usr/bin/env python3
"""
Generate the named appendix for the UI design-system report pair.

The appendix is generated, never typed. Both deliverables use counts in their
body text because names crowd out the argument, but a count is unactionable to
whoever has to do the work and unverifiable to anyone checking it. This script
is what turns the counts back into names.

It runs the two auditors that produced every figure in the report and captures
their output verbatim:

  - src/web-ui/scripts/audit-ui.py --appendix  (checklist locations)
  - src/web-ui/scripts/check-contrast.py       (measured contrast ratios)

It also runs the same auditor against the tree at BASELINE_REF, so the "where
was the problem" section names the locations that were actually fixed rather
than describing them. Both columns come from one ruler.

Re-run after either auditor or the UI changes, and commit what changes:

    python3 scripts/report/build_ui_appendix.py
"""

from __future__ import annotations

import datetime
import pathlib
import shutil
import subprocess
import sys
import tempfile

ROOT = pathlib.Path(__file__).resolve().parent.parent.parent
WEB_UI = ROOT / "src" / "web-ui"
OUT = ROOT / "docs" / "playbooks" / "ui-design-system-appendix.md"

# The tree this work started from. Section C is generated against it.
#
# Pinned to a commit, deliberately. This was `HEAD` while the work was
# uncommitted, which was correct then and silently wrong the moment the work
# was committed: the "before" column started measuring the fixed tree and the
# appendix shrank from 134,770 bytes to 17,786. A moving baseline makes the
# before/after table converge on zero difference over time, which is the one
# failure mode that looks like success.
BASELINE_REF = "e8b2899"

HEADER = """\
# Appendix — generated, not typed

**Generated:** {date}
**Generated by:** `python3 scripts/report/build_ui_appendix.py`
**Sources:** `src/web-ui/scripts/audit-ui.py` and `src/web-ui/scripts/check-contrast.py`,
both committed in this repository. Re-run either and these tables reproduce.

This appendix exists because the briefing and the companion both use counts, and a count
alone cannot be acted on or checked. Everything below is emitted by the auditors; no figure
in it was entered by hand.

**What this appendix deliberately omits.** It lists what the auditors can see in source
text and in the token file. It does not list anything that only exists at render time — a
class supplied through a computed `cn()` argument, a cursor inherited from a parent element,
or an accessible name supplied by a wrapping component. It also contains no screenshots and
no runtime measurements, because no browser was driven to produce this report. Absence from
a list below is not proof of correctness for those cases.

---

"""


def run(cmd: list[str], cwd: pathlib.Path = WEB_UI) -> str:
    proc = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True)
    if proc.returncode not in (0, 1):
        sys.stderr.write(proc.stderr)
        raise SystemExit(f"failed: {' '.join(cmd)}")
    return proc.stdout.rstrip()


def demote(md: str) -> str:
    """Push every heading down one level so the file keeps a single H1."""
    return "\n".join(("#" + ln) if ln.startswith("#") else ln for ln in md.split("\n"))


def baseline_appendix(tmp: pathlib.Path) -> tuple[str, str]:
    """Run today's auditors against BASELINE_REF and return (summary, appendix)."""
    archive = subprocess.run(
        ["git", "archive", BASELINE_REF, "src/web-ui"],
        cwd=ROOT, capture_output=True, check=True,
    ).stdout
    subprocess.run(["tar", "-x", "-C", str(tmp)], input=archive, check=True)
    base = tmp / "src" / "web-ui"
    (base / "scripts").mkdir(parents=True, exist_ok=True)
    for script in ("audit-ui.py", "check-contrast.py"):
        shutil.copy(WEB_UI / "scripts" / script, base / "scripts" / script)
    return (
        run(["python3", "scripts/audit-ui.py"], cwd=base),
        run(["python3", "scripts/audit-ui.py", "--appendix"], cwd=base),
    )


def main() -> int:
    checklist = demote(run(["python3", "scripts/audit-ui.py", "--appendix"]))
    contrast = run(["python3", "scripts/check-contrast.py"])
    summary = run(["python3", "scripts/audit-ui.py"])

    with tempfile.TemporaryDirectory() as tmp:
        before_summary, before_appendix = baseline_appendix(pathlib.Path(tmp))
    before_appendix = demote(before_appendix)

    body = [
        HEADER.format(date=datetime.date.today().isoformat()),
        "## A. Checklist audit — every location the auditor can see\n",
        "```",
        summary,
        "```\n",
        checklist,
        "\n---\n",
        "## B. Contrast — every measured token pair, both themes\n",
        "Ratios are computed from the OKLCH values in `src/web-ui/app/globals.css`:",
        "OKLCH to OKLab to linear sRGB to sRGB to relative luminance to ratio. `min 4.5`",
        "is WCAG AA for normal text; `min 3.0` is WCAG 1.4.11 for a non-text boundary that",
        "identifies a control. Rows marked `not enforced` are measured and printed on",
        "purpose — see the companion, §3.\n",
        "```",
        contrast,
        "```\n",
        "---\n",
        f"## C. Where the findings were — the tree at `{BASELINE_REF}`\n",
        "The same auditor, same thresholds, run against the tree this work started from.",
        "This is the actionable half of the appendix: every location below is a place a",
        "change was made, named by `file:line` as it stood before the change. Line numbers",
        "are pre-change and will not line up with the current files.\n",
        "```",
        before_summary,
        "```\n",
        before_appendix,
        "",
    ]

    OUT.write_text("\n".join(body))
    print(f"wrote {OUT.relative_to(ROOT)} ({OUT.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
